# Generated by Django 5.2.9 on 2025-12-14 21:30

import chatbot.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.CharField(default=chatbot.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('session_title', models.CharField(blank=True, help_text='Optional title for the session (auto-generated from first query)', max_length=255, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Session is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(default=chatbot.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Display name for the document', max_length=255)),
                ('file', models.FileField(help_text='Upload PDF document', upload_to=chatbot.models.upload_to_chatbot_documents)),
                ('description', models.TextField(blank=True, help_text='Optional description of the document', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Include in chatbot knowledge base')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.CharField(default=chatbot.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('user', 'User Question'), ('assistant', 'AI Response')], max_length=20)),
                ('content', models.TextField(help_text='Message content (query or answer)')),
                ('source_document_name', models.CharField(blank=True, help_text='Which document was used to answer the query', max_length=255, null=True)),
                ('source_document_url', models.URLField(blank=True, help_text='URL to the source document', null=True)),
                ('source_document_type', models.CharField(blank=True, help_text="Type of source: 'document' or 'publication'", max_length=50, null=True)),
                ('confidence', models.FloatField(blank=True, help_text='AI confidence score (0-1)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(help_text='The chat session this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='chatbot_cha_session_24e989_idx')],
            },
        ),
    ]
