# Generated by Django 5.2.6 on 2025-09-21 07:41

import django.db.models.deletion
import django.utils.timezone
import multimedia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryGroup',
            fields=[
                ('id', models.CharField(default=multimedia.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Group',
                'verbose_name_plural': 'Gallery Groups',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.CharField(default=multimedia.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('youtube_id', models.CharField(help_text='YouTube video ID for embedding', max_length=100)),
                ('youtube_url', models.URLField(blank=True, help_text='Full YouTube URL', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=multimedia.models.upload_to_podcast_thumbnails)),
                ('duration', models.CharField(help_text='Duration in MM:SS format', max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('guest', models.CharField(blank=True, help_text='Guest speaker or host', max_length=200, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Podcasts',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(default=multimedia.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('youtube_id', models.CharField(help_text='YouTube video ID for embedding', max_length=100)),
                ('youtube_url', models.URLField(blank=True, help_text='Full YouTube URL', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=multimedia.models.upload_to_video_thumbnails)),
                ('duration', models.CharField(help_text='Duration in MM:SS format', max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.CharField(default=multimedia.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('alt_text', models.CharField(help_text='Alt text for accessibility', max_length=200)),
                ('image', models.ImageField(upload_to=multimedia.models.upload_to_gallery_images)),
                ('caption', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within the group')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='multimedia.gallerygroup')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['group', 'order', '-created_at'],
            },
        ),
    ]
