# Generated by Django 5.2.9 on 2026-02-06 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Poll question or title', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the poll')),
                ('category', models.CharField(blank=True, help_text='Category or topic (e.g., Legislation, Budget, Governance)', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', help_text='Current status of the poll', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, help_text='When the poll becomes active', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When the poll closes', null=True)),
                ('allow_multiple_votes', models.BooleanField(default=False, help_text='Allow users to vote multiple times')),
                ('show_results_before_voting', models.BooleanField(default=False, help_text='Show results before user votes')),
                ('featured', models.BooleanField(default=False, help_text='Feature this poll on the homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Title of the trivia set', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short description shown on the card')),
                ('image', models.ImageField(blank=True, help_text='Optional cover image for the trivia card', null=True, upload_to='trivia/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show on Citizens Voice page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trivia',
                'verbose_name_plural': 'Trivia',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='XPollEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional label for admin (e.g. poll topic)', max_length=200)),
                ('embed_html', models.TextField(help_text='Paste the full embed from Twitter: the <blockquote class="twitter-tweet">...</blockquote> part.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'X Poll Embed',
                'verbose_name_plural': 'X Poll Embeds',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Option text', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='multimedia.poll')),
            ],
            options={
                'verbose_name': 'Poll Option',
                'verbose_name_plural': 'Poll Options',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Voter's IP address", null=True)),
                ('session_id', models.CharField(blank=True, help_text='Session identifier', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='multimedia.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='multimedia.poll')),
            ],
            options={
                'verbose_name': 'Poll Vote',
                'verbose_name_plural': 'Poll Votes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question shown on the card')),
                ('answer_text', models.TextField(blank=True, help_text='Optional answer to reveal (e.g. for quiz-style trivia)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within the trivia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trivia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='multimedia.trivia')),
            ],
            options={
                'verbose_name': 'Trivia Question',
                'verbose_name_plural': 'Trivia Questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriviaOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Option text', max_length=500)),
                ('is_correct', models.BooleanField(default=False, help_text='Whether this is the correct answer')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='multimedia.triviaquestion')),
            ],
            options={
                'verbose_name': 'Trivia Option',
                'verbose_name_plural': 'Trivia Options',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
