# Generated by Django 5.2.6 on 2025-10-26 11:06

import django.db.models.deletion
import django.utils.timezone
import focusareas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.CharField(default=focusareas.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Short description for cards and previews')),
                ('image', models.ImageField(upload_to=focusareas.models.upload_to_focus_area_images)),
                ('overview_summary', models.TextField(help_text='Detailed summary for the overview section')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Planned', 'Planned')], default='Active', max_length=20)),
                ('start_date', models.CharField(help_text="E.g., 'January 2020'", max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Focus Area',
                'verbose_name_plural': 'Focus Areas',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FocusAreaActivity',
            fields=[
                ('id', models.CharField(default=focusareas.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('focus_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='focusareas.focusarea')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FocusAreaMilestone',
            fields=[
                ('id', models.CharField(default=focusareas.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=10)),
                ('event', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('focus_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='focusareas.focusarea')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FocusAreaObjective',
            fields=[
                ('id', models.CharField(default=focusareas.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('focus_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='focusareas.focusarea')),
            ],
            options={
                'verbose_name': 'Objective',
                'verbose_name_plural': 'Objectives',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FocusAreaOutcome',
            fields=[
                ('id', models.CharField(default=focusareas.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('metric', models.CharField(help_text="E.g., '50+ Reports', '500+ Trained'", max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('focus_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='focusareas.focusarea')),
            ],
            options={
                'verbose_name': 'Outcome',
                'verbose_name_plural': 'Outcomes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FocusAreaPartner',
            fields=[
                ('id', models.CharField(default=focusareas.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Government', 'Government'), ('Donor', 'Donor'), ('NGO Partners', 'NGO Partners'), ('International Partner', 'International Partner'), ('Private Sector', 'Private Sector'), ('Research Partners', 'Research Partners'), ('Media Partners', 'Media Partners')], max_length=100)),
                ('role', models.TextField(help_text='Description of their role in this focus area')),
                ('order', models.IntegerField(default=0)),
                ('focus_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='focusareas.focusarea')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['order'],
            },
        ),
    ]
