# Generated by Django 5.2.6 on 2025-10-26 10:52

import focusareas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusarea',
            name='image',
            field=models.ImageField(default='default-focus-area.jpg', upload_to=focusareas.models.upload_to_focus_area_images),
            preserve_default=False,
        ),
    ]
