# Generated by Django 5.2.6 on 2025-10-26 13:02

import django.db.models.deletion
import django.utils.timezone
import focusareas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusAreaCollection',
            fields=[
                ('id', models.CharField(default=focusareas.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name of the collection (e.g., 'Strategic Priorities', 'Community Programs')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description for this collection')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Focus Area Collection',
                'verbose_name_plural': 'Focus Area Collections',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='focusarea',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Optional collection for organizing focus areas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_areas', to='focusareas.focusareacollection'),
        ),
    ]
