# Generated by Django 5.2.6 on 2025-10-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focusareas', '0002_focusareacollection_focusarea_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focusarea',
            name='collection',
        ),
        migrations.DeleteModel(
            name='FocusAreaCollection',
        ),
    ]
