# Generated by Django 5.2.6 on 2025-10-26 13:30

import django.db.models.deletion
import django.utils.timezone
import focusareas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusareas', '0003_remove_focusarea_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focusarea',
            name='description',
        ),
        migrations.RemoveField(
            model_name='focusarea',
            name='image',
        ),
        migrations.RemoveField(
            model_name='focusarea',
            name='overview_summary',
        ),
        migrations.RemoveField(
            model_name='focusarea',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='focusarea',
            name='status',
        ),
        migrations.RemoveField(
            model_name='focusarea',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='focusarea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='FocusAreaBasicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Short description for cards and previews')),
                ('image', models.ImageField(upload_to=focusareas.models.upload_to_focus_area_images)),
                ('overview_summary', models.TextField(help_text='Detailed summary for the overview section')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Planned', 'Planned')], default='Active', max_length=20)),
                ('start_date', models.CharField(help_text="E.g., 'January 2020'", max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('focus_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='focusareas.focusarea')),
            ],
            options={
                'verbose_name': 'FocusArea Basic Information',
                'verbose_name_plural': 'FocusArea Basic Information',
            },
        ),
    ]
