# Generated by Django 5.2.6 on 2025-10-26 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusareas', '0004_remove_focusarea_description_remove_focusarea_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusareabasicinformation',
            name='focus_area',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_information', to='focusareas.focusarea'),
        ),
    ]
