# Generated by Django 5.2.6 on 2025-10-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusareas', '0005_alter_focusareabasicinformation_focus_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='focusarea',
            options={'ordering': ['title'], 'verbose_name': 'Focus Area', 'verbose_name_plural': 'Focus Areas'},
        ),
        migrations.RemoveField(
            model_name='focusarea',
            name='order',
        ),
        migrations.RemoveField(
            model_name='focusareabasicinformation',
            name='description',
        ),
        migrations.AddField(
            model_name='focusareabasicinformation',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
    ]
