# Generated by Django 5.2.6 on 2025-10-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusareas', '0006_alter_focusarea_options_remove_focusarea_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusareaactivity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
