# Generated by Django 5.2.6 on 2025-10-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focusareas', '0007_focusareaactivity_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focusareaactivity',
            name='description',
        ),
    ]
