# Generated by Django 5.2.6 on 2025-10-27 17:37

import django.db.models.deletion
import focusareas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusareas', '0008_remove_focusareaactivity_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusAreaResources',
            fields=[
                ('id', models.CharField(default=focusareas.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resources/focus-area')),
                ('order', models.IntegerField(default=0)),
                ('focus_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='focusareas.focusarea')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['order', 'name'],
            },
        ),
    ]
