# Generated by Django 5.2.6 on 2025-10-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focusareas', '0009_focusarearesources'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='focusareabasicinformation',
            options={'verbose_name': 'Basic Information', 'verbose_name_plural': 'Basic Information'},
        ),
    ]
