# Generated by Django 5.2.6 on 2025-09-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE contact_contact DROP COLUMN IF EXISTS first_name;",
            reverse_sql="ALTER TABLE contact_contact ADD COLUMN first_name VARCHAR(100);"
        ),
        migrations.RunSQL(
            "ALTER TABLE contact_contact DROP COLUMN IF EXISTS last_name;",
            reverse_sql="ALTER TABLE contact_contact ADD COLUMN last_name VARCHAR(100);"
        ),
        migrations.RunSQL(
            "ALTER TABLE contact_contact DROP COLUMN IF EXISTS updated_at;",
            reverse_sql="ALTER TABLE contact_contact ADD COLUMN updated_at TIMESTAMP;"
        ),
        migrations.RunSQL(
            "ALTER TABLE contact_contact DROP COLUMN IF EXISTS is_responded;",
            reverse_sql="ALTER TABLE contact_contact ADD COLUMN is_responded BOOLEAN DEFAULT FALSE;"
        ),
        migrations.RunSQL(
            "ALTER TABLE contact_contact ADD COLUMN IF NOT EXISTS name VARCHAR(100);",
            reverse_sql="ALTER TABLE contact_contact DROP COLUMN IF EXISTS name;"
        ),
    ]
