# Generated by Django 5.2.6 on 2025-09-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20250922_0638'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE contact_contact DROP CONSTRAINT IF EXISTS contact_contact_pkey;",
            reverse_sql="ALTER TABLE contact_contact ADD PRIMARY KEY (id);"
        ),
        migrations.RunSQL(
            "ALTER TABLE contact_contact ALTER COLUMN id TYPE INTEGER USING id::integer;",
            reverse_sql="ALTER TABLE contact_contact ALTER COLUMN id TYPE VARCHAR(255);"
        ),
        migrations.RunSQL(
            "ALTER TABLE contact_contact ADD PRIMARY KEY (id);",
            reverse_sql="ALTER TABLE contact_contact DROP CONSTRAINT IF EXISTS contact_contact_pkey;"
        ),
        migrations.RunSQL(
            "ALTER TABLE contact_newsletter DROP CONSTRAINT IF EXISTS contact_newsletter_pkey;",
            reverse_sql="ALTER TABLE contact_newsletter ADD PRIMARY KEY (id);"
        ),
        migrations.RunSQL(
            "ALTER TABLE contact_newsletter ALTER COLUMN id TYPE INTEGER USING id::integer;",
            reverse_sql="ALTER TABLE contact_newsletter ALTER COLUMN id TYPE VARCHAR(255);"
        ),
        migrations.RunSQL(
            "ALTER TABLE contact_newsletter ADD PRIMARY KEY (id);",
            reverse_sql="ALTER TABLE contact_newsletter DROP CONSTRAINT IF EXISTS contact_newsletter_pkey;"
        ),
    ]
