# Generated by Django 5.2.6 on 2025-09-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20250922_0638'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS contact_contact CASCADE;",
            reverse_sql="-- Cannot reverse table drop"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS contact_newsletter CASCADE;",
            reverse_sql="-- Cannot reverse table drop"
        ),
        migrations.RunSQL(
            """
            CREATE TABLE contact_contact (
                id SERIAL PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                email VARCHAR(254) NOT NULL,
                phone VARCHAR(20) DEFAULT '',
                subject VARCHAR(200) NOT NULL,
                message TEXT NOT NULL,
                organization VARCHAR(100) DEFAULT '',
                inquiry_type VARCHAR(20) DEFAULT 'general' CHECK (inquiry_type IN ('general', 'training', 'consultancy', 'partnership', 'other')),
                created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS contact_contact CASCADE;"
        ),
        migrations.RunSQL(
            """
            CREATE TABLE contact_newsletter (
                id SERIAL PRIMARY KEY,
                email VARCHAR(254) UNIQUE NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS contact_newsletter CASCADE;"
        ),
    ]
