# Generated by Django 5.2.6 on 2025-09-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20250922_0706'),
        ('contact', '0003_auto_20250922_0709'),
    ]

    operations = [
    ]
