# Generated by Django 5.2.6 on 2025-09-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_merge_0003_auto_20250922_0706_0003_auto_20250922_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
