# Generated by Django 5.2.6 on 2025-09-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_update_inquiry_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='inquiry_type',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('donate', 'Donation Inquiry'), ('career', 'Career Opportunities'), ('fellowships', 'Fellowship Programs'), ('membership', 'Membership'), ('announcements', 'Announcements')], default='general', max_length=20),
        ),
    ]
