# Generated by Django 5.2.6 on 2025-09-30 16:21

import django.utils.timezone
import getinvolved.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerOpportunity',
            fields=[
                ('id', models.CharField(default=getinvolved.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('Full-time', 'Full-time Position'), ('Internship', 'Internship'), ('Fellowship', 'Fellowship'), ('Consultancy', 'Consultancy'), ('Part-time', 'Part-time Position')], max_length=100)),
                ('location', models.CharField(default='Kampala, Uganda', max_length=200)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(help_text='Main responsibilities for this position')),
                ('requirements', models.TextField(help_text='Required qualifications and skills')),
                ('how_to_apply', models.TextField(help_text='Application instructions and process')),
                ('deadline', models.DateField(help_text='Application deadline')),
                ('posted_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=getinvolved.models.upload_to_career_images)),
                ('slug', models.CharField(blank=True, max_length=500, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Opportunity',
                'verbose_name_plural': 'Career Opportunities',
                'ordering': ['-created_at'],
            },
        ),
    ]
