# Generated by Django 5.2.6 on 2025-09-30 16:53

import django.utils.timezone
import getinvolved.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getinvolved', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.CharField(default=getinvolved.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('General', 'General Announcement'), ('Event', 'Event Announcement'), ('Program', 'Program Update'), ('Partnership', 'Partnership Announcement'), ('Achievement', 'Achievement/Award'), ('Policy', 'Policy Update'), ('Urgent', 'Urgent Notice')], max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('summary', models.TextField(help_text='Brief summary or excerpt')),
                ('content', models.TextField(help_text='Full announcement content')),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, help_text='Optional expiry date for time-sensitive announcements', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the announcement is currently active')),
                ('featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=getinvolved.models.upload_to_announcement_images)),
                ('slug', models.CharField(blank=True, max_length=500, unique=True)),
                ('external_link', models.URLField(blank=True, help_text='Optional external link for more information', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
