# Generated by Django 5.2.9 on 2026-02-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizensVoiceFeedbackLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_mp_form_url', models.URLField(blank=True, help_text="Google form URL for 'Ask your MP'", max_length=500)),
                ('comment_bill_form_url', models.URLField(blank=True, help_text="Google form URL for 'Comment on a bill'", max_length=500)),
                ('feedback_law_form_url', models.URLField(blank=True, help_text="Google form URL for 'Feedback on a law'", max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Citizens Voice feedback links',
                'verbose_name_plural': 'Citizens Voice feedback links',
            },
        ),
        migrations.CreateModel(
            name='PageHeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.CharField(choices=[('about', 'About Us'), ('contact', 'Contact Us'), ('citizens-voice', 'Citizens Voice'), ('multimedia', 'Multimedia'), ('get-involved', 'Get Involved'), ('resources', 'Resources')], help_text='The page this hero image is for', max_length=50, unique=True)),
                ('page_name', models.CharField(blank=True, help_text='Display name for the page (auto-filled from slug if empty)', max_length=100)),
                ('image', models.ImageField(help_text='Hero image for this page', upload_to='page_heroes/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this hero image is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Hero Image',
                'verbose_name_plural': 'Page Hero Images',
                'ordering': ['page_slug'],
            },
        ),
    ]
