# Generated by Django 5.2.6 on 2025-12-09 07:10

import django.utils.timezone
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.CharField(default=home.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Hero slide image', upload_to=home.models.upload_to_hero_slides)),
                ('title', models.CharField(help_text='Slide title/alt text', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Display this slide in the slider')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'title'],
            },
        ),
    ]
