# Generated by Django 5.2.6 on 2025-10-23 04:14

import django.db.models.deletion
import django.utils.timezone
import fellowships.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.CharField(default=fellowships.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., 2025 Cohort', max_length=200)),
                ('year', models.IntegerField()),
                ('overview', models.TextField(help_text='Overview description of this cohort')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='cohorts/hero/')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cohort',
                'verbose_name_plural': 'Cohorts',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='CohortEvent',
            fields=[
                ('id', models.CharField(default=fellowships.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='fellowships.cohort')),
            ],
            options={
                'verbose_name': 'Cohort Event',
                'verbose_name_plural': 'Cohort Events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='CohortGalleryImage',
            fields=[
                ('id', models.CharField(default=fellowships.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='cohorts/gallery/')),
                ('caption', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='fellowships.cohort')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CohortProject',
            fields=[
                ('id', models.CharField(default=fellowships.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cohorts/projects/')),
                ('project_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='fellowships.cohort')),
            ],
            options={
                'verbose_name': 'Cohort Project',
                'verbose_name_plural': 'Cohort Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fellow',
            fields=[
                ('id', models.CharField(default=fellowships.models.generate_uuid, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='cohorts/fellows/')),
                ('position', models.CharField(blank=True, help_text='e.g., Research Fellow', max_length=200, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellows', to='fellowships.cohort')),
            ],
            options={
                'verbose_name': 'Fellow',
                'verbose_name_plural': 'Fellows',
                'ordering': ['name'],
            },
        ),
    ]
