# Generated by Django 5.2.6 on 2025-11-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellowships', '0002_remove_cohort_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cohorts/'),
        ),
    ]
