# Generated by Django 5.2.9 on 2025-12-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fellowships', '0003_cohort_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortBasicInfo',
            fields=[
            ],
            options={
                'verbose_name': 'Cohort Basic Info',
                'verbose_name_plural': 'Cohort Basic Info',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fellowships.cohort',),
        ),
    ]
