# Generated by Django 5.2.6 on 2025-11-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallToActionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Join Us in Building a Better Uganda', max_length=255)),
                ('description', models.TextField(help_text='Section description')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Call to Action Section',
                'verbose_name_plural': 'Call to Action Section',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About CEPA', max_length=255)),
                ('description', models.TextField(help_text='Main hero description')),
                ('hero_image', models.ImageField(blank=True, help_text='Hero background image', null=True, upload_to='hero/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='OurStorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Story', max_length=255)),
                ('description', models.TextField(help_text='Section description')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Our Story Section',
                'verbose_name_plural': 'Our Story Section',
            },
        ),
        migrations.CreateModel(
            name='StatCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(help_text='Numeric value (e.g., 10, 50, 100)')),
                ('label', models.CharField(help_text="Label (e.g., 'Years of Impact', 'Policy Reports')", max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stat Card',
                'verbose_name_plural': 'Stat Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhatSetsUsApartSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='What Sets CEPA Apart', max_length=255)),
                ('description', models.TextField(help_text='Section description')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'What Sets Us Apart Section',
                'verbose_name_plural': 'What Sets Us Apart Section',
            },
        ),
        migrations.CreateModel(
            name='WhoWeAreSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Who We Are', max_length=255)),
                ('description', models.TextField(help_text='Section description')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Who We Are Section',
                'verbose_name_plural': 'Who We Are Section',
            },
        ),
        migrations.CreateModel(
            name='OurStoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Emoji icon', max_length=10)),
                ('title', models.CharField(help_text="e.g., 'Our Vision', 'Our Mission', 'Our Values'", max_length=255)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='about.ourstorysection')),
            ],
            options={
                'verbose_name': 'Our Story Card',
                'verbose_name_plural': 'Our Story Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhatSetsUsApartCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='about.whatsetsusapartsection')),
            ],
            options={
                'verbose_name': 'What Sets Us Apart Card',
                'verbose_name_plural': 'What Sets Us Apart Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhoWeAreFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Emoji icon', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='about.whowearesection')),
            ],
            options={
                'verbose_name': 'Who We Are Feature',
                'verbose_name_plural': 'Who We Are Features',
                'ordering': ['order'],
            },
        ),
    ]
