# Generated by Django 5.2.6 on 2025-11-12 11:55

from django.db import migrations


def populate_about_page_data(apps, schema_editor):
    """Populate About page with initial content from frontend"""
    HeroSection = apps.get_model('about', 'HeroSection')
    WhoWeAreSection = apps.get_model('about', 'WhoWeAreSection')
    WhoWeAreFeature = apps.get_model('about', 'WhoWeAreFeature')
    StatCard = apps.get_model('about', 'StatCard')
    OurStorySection = apps.get_model('about', 'OurStorySection')
    OurStoryCard = apps.get_model('about', 'OurStoryCard')
    WhatSetsUsApartSection = apps.get_model('about', 'WhatSetsUsApartSection')
    WhatSetsUsApartCard = apps.get_model('about', 'WhatSetsUsApartCard')
    CallToActionSection = apps.get_model('about', 'CallToActionSection')

    # Create Hero Section
    hero = HeroSection.objects.create(
        title="About CEPA",
        description="The Centre for Policy Analysis (CEPA) is a leading think tank in Uganda dedicated to shaping public policy and strengthening democratic governance through high-quality research, collaboration, and citizen engagement."
    )

    # Create Who We Are Section
    who_we_are = WhoWeAreSection.objects.create(
        title="Who We Are",
        description="The Centre for Policy Analysis (CEPA) is a leading think tank in Uganda dedicated to shaping public policy and strengthening democratic governance through high-quality research, collaboration, and citizen engagement."
    )

    # Create Who We Are Features
    WhoWeAreFeature.objects.create(
        section=who_we_are,
        icon="🔬",
        title="Evidence-Based Research",
        description="We conduct rigorous, independent research to inform policy decisions and strengthen democratic governance in Uganda.",
        order=1
    )
    WhoWeAreFeature.objects.create(
        section=who_we_are,
        icon="🤝",
        title="Collaborative Approach",
        description="We work closely with parliamentarians, government officials, civil society, and citizens to drive meaningful reforms.",
        order=2
    )
    WhoWeAreFeature.objects.create(
        section=who_we_are,
        icon="🏛️",
        title="Parliament Watch Uganda",
        description="Our flagship program empowers stakeholders to engage with legislative processes and promote transparency.",
        order=3
    )

    # Create Stat Cards
    StatCard.objects.create(value=10, label="Years of Impact", order=1)
    StatCard.objects.create(value=50, label="Policy Reports", order=2)
    StatCard.objects.create(value=100, label="Stakeholders Engaged", order=3)
    StatCard.objects.create(value=15, label="Partner Organizations", order=4)

    # Create Our Story Section
    our_story = OurStorySection.objects.create(
        title="Our Story",
        description="CEPA was established with a vision to create a more transparent, accountable, and democratic Uganda through rigorous policy research and advocacy."
    )

    # Create Our Story Cards
    OurStoryCard.objects.create(
        section=our_story,
        icon="🎯",
        title="Our Vision",
        description="To build a democratic society where governance systems and public institutions are transparent, accountable, and responsive to the needs of all citizens.",
        order=1
    )
    OurStoryCard.objects.create(
        section=our_story,
        icon="⚖️",
        title="Our Mission",
        description="To shape public policy and strengthen democratic governance by delivering high-quality research, fostering collaboration, and empowering citizens to engage meaningfully with decision-making processes.",
        order=2
    )
    OurStoryCard.objects.create(
        section=our_story,
        icon="🌟",
        title="Our Values",
        description="Integrity, independence, excellence, and commitment to democratic principles guide all our work and interactions.",
        order=3
    )

    # Create What Sets Us Apart Section
    what_sets_us_apart = WhatSetsUsApartSection.objects.create(
        title="What Sets CEPA Apart",
        description="CEPA distinguishes itself through innovative approaches and collaborative methodologies that drive meaningful change in Uganda's governance landscape."
    )

    # Create What Sets Us Apart Cards
    WhatSetsUsApartCard.objects.create(
        section=what_sets_us_apart,
        title="A Unique Consortium Model",
        description="CEPA integrates the expertise and resources of various partner organizations, creating a robust platform for multi-disciplinary approaches to governance challenges.",
        order=1
    )
    WhatSetsUsApartCard.objects.create(
        section=what_sets_us_apart,
        title="Thought Leadership and Innovation",
        description="We pioneer new methodologies and approaches to policy analysis, setting standards for evidence-based governance research in Uganda and beyond.",
        order=2
    )

    # Create Call to Action Section
    CallToActionSection.objects.create(
        title="Join Us in Building a Better Uganda",
        description="Whether through research, advocacy, or direct engagement, there are many ways to contribute to our mission of strengthening democratic governance and promoting transparency in Uganda."
    )


def reverse_populate_about_page_data(apps, schema_editor):
    """Remove all about page data"""
    HeroSection = apps.get_model('about', 'HeroSection')
    WhoWeAreSection = apps.get_model('about', 'WhoWeAreSection')
    WhoWeAreFeature = apps.get_model('about', 'WhoWeAreFeature')
    StatCard = apps.get_model('about', 'StatCard')
    OurStorySection = apps.get_model('about', 'OurStorySection')
    OurStoryCard = apps.get_model('about', 'OurStoryCard')
    WhatSetsUsApartSection = apps.get_model('about', 'WhatSetsUsApartSection')
    WhatSetsUsApartCard = apps.get_model('about', 'WhatSetsUsApartCard')
    CallToActionSection = apps.get_model('about', 'CallToActionSection')

    # Delete all records
    HeroSection.objects.all().delete()
    WhoWeAreFeature.objects.all().delete()
    WhoWeAreSection.objects.all().delete()
    StatCard.objects.all().delete()
    OurStoryCard.objects.all().delete()
    OurStorySection.objects.all().delete()
    WhatSetsUsApartCard.objects.all().delete()
    WhatSetsUsApartSection.objects.all().delete()
    CallToActionSection.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_about_page_data, reverse_populate_about_page_data),
    ]
