# Generated by Django 5.2.6 on 2025-11-12 12:45

from django.db import migrations


def populate_team_members(apps, schema_editor):
    """
    Populate Team Members with existing team data.
    Note: Profile images need to be uploaded through Django admin after running this migration.
    """
    TeamMember = apps.get_model('about', 'TeamMember')

    team_members = [
        {"name": "Chemonges M. Timothy", "role": "Executive Director", "linkedin_url": "https://www.linkedin.com/in/timothy-chemonges-1a47a4173/?originalSubdomain=ug", "order": 1},
        {"name": "Angella Hilda Kemirembe", "role": "Communication Manager", "linkedin_url": "https://ug.linkedin.com/in/angella-hilda-kemirembe-35111a9b", "order": 2},
        {"name": "Joseph Tahinduka", "role": "Programmes Officer", "linkedin_url": "https://www.linkedin.com/in/tahinduka-joseph-8ba5401b5/", "order": 3},
        {"name": "Rebecca Karagwa", "role": "Programmes Associate", "linkedin_url": "https://www.linkedin.com/in/rebecca-karagwa-10a7b3133/", "order": 4},
        {"name": "Thembo Kahungu Misairi", "role": "Programme Associate", "linkedin_url": "", "order": 5},
        {"name": "Prisca Wanyenya", "role": "Programme Associate", "linkedin_url": "", "order": 6},
        {"name": "Dominic Ochola", "role": "Programme Associate", "linkedin_url": "https://www.linkedin.com/in/dominic-ochola", "order": 7},
        {"name": "Rashid Kasule", "role": "Production Lead", "linkedin_url": "", "order": 8},
        {"name": "Timothy Ainebyoona", "role": "Volunteer", "linkedin_url": "http://www.LinkedIn.com/in/timothy-ainebyoona-31906a216", "order": 9},
        {"name": "Faith Uwizeye", "role": "Volunteer", "linkedin_url": "", "order": 10},
        {"name": "Fraide Solomon", "role": "Volunteer", "linkedin_url": "https://www.linkedin.com/in/fraide-solomon-101491311", "order": 11},
    ]

    for member_data in team_members:
        TeamMember.objects.create(
            name=member_data["name"],
            role=member_data["role"],
            linkedin_url=member_data["linkedin_url"] if member_data["linkedin_url"] else None,
            order=member_data["order"],
            profile_image='',  # Images need to be uploaded through admin
            is_active=True
        )


def reverse_populate_team_members(apps, schema_editor):
    """Remove all team members"""
    TeamMember = apps.get_model('about', 'TeamMember')
    TeamMember.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_teammember'),
    ]

    operations = [
        migrations.RunPython(populate_team_members, reverse_populate_team_members),
    ]
