# Generated by Django 5.2.6 on 2025-11-12 13:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_populate_team_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Partner organization name', max_length=255)),
                ('full_name', models.CharField(blank=True, help_text='Full organization name (optional)', max_length=500, null=True)),
                ('logo', models.ImageField(help_text='Partner logo', upload_to='partners/')),
                ('website_url', models.URLField(blank=True, help_text='Partner website URL (optional)', max_length=500, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['order', 'name'],
            },
        ),
    ]
