# Generated by Django 5.2.6 on 2025-11-12 13:20

from django.db import migrations


def populate_partners(apps, schema_editor):
    """
    Populate Partners with existing partner data.
    Note: Partner logos need to be uploaded through Django admin after running this migration.
    The logo files are currently in /public/partners/ on the frontend.
    """
    Partner = apps.get_model('about', 'Partner')

    partners = [
        {"name": "GRSP", "full_name": "Global Road Safety Partnership", "order": 1},
        {"name": "UPFYA", "full_name": "Uganda Parliamentary Forum for Youth Affairs", "order": 2},
        {"name": "Twaweza", "full_name": "Twaweza East Africa", "order": 3},
        {"name": "WFD", "full_name": "Westminster Foundation for Democracy", "order": 4},
        {"name": "KAS", "full_name": "Konrad-Adenauer-Stiftung", "order": 5},
        {"name": "GAPP", "full_name": "Global Action for Policy and Practice", "order": 6},
        {"name": "Diakonia", "full_name": "Diakonia", "order": 7},
        {"name": "NED", "full_name": "National Endowment for Democracy", "order": 8},
        {"name": "AFIDEP", "full_name": "African Institute for Development Policy", "order": 9},
    ]

    for partner_data in partners:
        Partner.objects.create(
            name=partner_data["name"],
            full_name=partner_data["full_name"],
            order=partner_data["order"],
            logo='',  # Logos need to be uploaded through admin
            website_url=None,
            is_active=True
        )


def reverse_populate_partners(apps, schema_editor):
    """Remove all partners"""
    Partner = apps.get_model('about', 'Partner')
    Partner.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_partner'),
    ]

    operations = [
        migrations.RunPython(populate_partners, reverse_populate_partners),
    ]
