# Generated by Django 5.2.6 on 2025-09-09 02:52

import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.CharField(default=resources.models.generate_uuid, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=resources.models.upload_to_blog_images),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(default=resources.models.generate_uuid, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=resources.models.upload_to_event_images),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='id',
            field=models.CharField(default=resources.models.generate_uuid, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=resources.models.upload_to_news_images),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.CharField(default=resources.models.generate_uuid, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=resources.models.upload_to_publication_pdfs),
        ),
    ]
