# Generated by Django 5.2.6 on 2025-09-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_blogpost_date_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
