# Generated by Django 5.2.9 on 2026-01-29 09:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_add_views_and_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate from title (normal text).', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
